### ISSUE TITLE
ReferenceError: Meteor is not defined

### ISSUE THREAD

**Issue by dan335** [xolvio/jasmine-unit#24] opened 2014-07-12 17:20 UTC
DEBUG=1 VELOCITY_DEBUG=1 JASMINE_DEBUG=1 meteor --settings settings.json

=> Started proxy.
=> Started MongoDB.  
W20140712-10:18:22.117(-7)? (STDERR) 
W20140712-10:18:22.153(-7)? (STDERR) /home/dan/meteor/gridgame/.meteor/local/build/programs/server/boot.js:186
W20140712-10:18:22.153(-7)? (STDERR) }).run();
W20140712-10:18:22.153(-7)? (STDERR)    ^
W20140712-10:18:22.153(-7)? (STDERR) ReferenceError: Meteor is not defined
W20140712-10:18:22.153(-7)? (STDERR)     at app/game/lib/settings.js:9:5
W20140712-10:18:22.153(-7)? (STDERR)     at app/game/lib/settings.js:184:3
W20140712-10:18:22.154(-7)? (STDERR)     at /home/dan/meteor/gridgame/.meteor/local/build/programs/server/boot.js:155:10
W20140712-10:18:22.154(-7)? (STDERR)     at Array.forEach (native)
W20140712-10:18:22.154(-7)? (STDERR)     at Function._.each._.forEach (/home/dan/.meteor/tools/858c88b520/lib/node_modules/underscore/underscore.js:79:11)
W20140712-10:18:22.154(-7)? (STDERR)     at /home/dan/meteor/gridgame/.meteor/local/build/programs/server/boot.js:82:5
=> Exited with code: 8

The line that is causing the error is

if (Meteor.isServer && process.env.NODE_ENV == 'development') {

Sorry I can't post an app.

**Comment by dan335** [comment] 2014-07-12 17:30
This happens after adding the velocity-quick-start package.

**Comment by alanning** [comment] 2014-07-12 19:02
If you run with `mrt`, does that make a difference?  It seems like the velocity stuff isn't even being loaded.

**Comment by dan335** [comment] 2014-07-12 19:11
I tried DEBUG=1 VELOCITY_DEBUG=1 JASMINE_DEBUG=1 mrt --settings settings.json but get the same error.

**Comment by SamHatoum** [comment] 2014-07-12 19:13
could you perhaps show us a directory tree of your project?

**Comment by dan335** [comment] 2014-07-12 19:21
http://imgur.com/c4XPV5T,dq5llgf#0
http://imgur.com/c4XPV5T,dq5llgf#1

If there are folders that are closed that you want to see let me know.  Or if there are files that would help.

**Comment by dan335** [comment] 2014-07-12 19:30
Oops, the images were from the wrong branch, here are correct ones.  It's the same but with velocity.

http://imgur.com/58bgFCE,zX59Vd4
http://imgur.com/58bgFCE,zX59Vd4#1

**Comment by dan335** [comment] 2014-07-12 19:54
Here's an app with the crash.

https://github.com/dan335/velocity_crash

**Comment by alanning** [comment] 2014-07-12 19:54
If you do these steps, what do you see?

```
$ cd ~/tmp
$ meteor create --example leaderboard
$ cd leaderboard
$ mrt add velocity-quick-start
$ DEBUG=1 VELOCITY_DEBUG=1 JASMINE_DEBUG=1 mrt
CTRL-C
$ DEBUG=1 VELOCITY_DEBUG=1 JASMINE_DEBUG=1 mrt 
```

**Comment by dan335** [comment] 2014-07-12 19:56
It's either iron-router or font-awesome packages with this line.

if (Meteor.isServer && process.env.NODE_ENV == 'development') {

**Comment by alanning** [comment] 2014-07-12 20:00
This is due to `.meteor/packages` getting erased.

Looks like the quick-start is wiping it out for some reason.

**Comment by alanning** [comment] 2014-07-12 20:02
Hmm, I can't seem to make it happen on my local machine.  Can you post the version of your `.meteor/packages` file that triggers this issue, please?

**Comment by dan335** [comment] 2014-07-12 20:08
.meteor/packages is empty

**Comment by dan335** [comment] 2014-07-12 20:13
meteor create test2
cd test2
mrt add velocity-quick-start
meteor  Everything works
mrt add iron-router
meteor  Everything works
mrt add font-awesome
meteor  Everything works, confused because last time this broke it.
Saw your post and looked at .meteor/packages in the other app
Came back to test2 app
mrt add cookies
meteor Crashed this time.

**Comment by dan335** [comment] 2014-07-12 20:16
Also somewhere in there I added the line if (Meteor.isServer && process.env.NODE_ENV == 'development') {

**Comment by alanning** [comment] 2014-07-12 20:24
The default `test2.js` file that Meteor creates starts with `if (Meteor.isClient) {` so it would crash whether or not you add the `(Meteor.isServer && ...)` line if the `.meteor/packages` file has been wiped (due to `standard-app-packages` not being loaded).

Can you try the repro process again (`test3`) with DEBUG=1 in front of all those `meteor` and `mrt` commands, please?

Like this:

```
$ cd test2
$ DEBUG=1 mrt add velocity-quick-start
$ DEBUG=1 meteor
...
```

**Comment by dan335** [comment] 2014-07-12 20:47
I made a test3 and did the same steps with DEBUG=1 and everything works, can't get it to crash.

**Comment by alanning** [comment] 2014-07-12 21:07
Ugh, heisenbugs are the worst.  Does it work now with your main app?

I'll modify the code that updates the `.meteor/packages` file to see if that helps but would be nice to have a stable reproduction.

**Comment by dan335** [comment] 2014-07-12 21:21
My app and test2 still break, tried a couple more times to get test3 to break but couldn't.

**Comment by dan335** [comment] 2014-07-12 21:53
I went back to my app.  Copied .meteor/packages from a different branch to the velocity branch.  Ran mrt add velocity-quick-start.  It looks like velocity is working now but I got this.  Probably a different issue.  

```
Error loading app files Cannot read property 'fn' of undefined TypeError: Cannot read property 'fn' of undefined
I20140712-14:47:20.230(-7)?   at /home/dan/meteor/gridgame/client/lib/bootstrap-slider.js:654:3
<snip/>
```

The bootstrap-slider is at https://github.com/seiyria/bootstrap-slider  The line number is different for some reason.  Here is the code that errors

```
$.fn.slider = function (option) {
    if (typeof option === 'string' && option !== 'refresh') {
        var args = Array.prototype.slice.call(arguments, 1);
        return invokePublicMethod.call(this, option, args);
    } else {
        return createNewSliderInstance.call(this, option);
    }
};
```

Edit: snipped log output - AVL

**Comment by alanning** [comment] 2014-07-12 22:01
That looks like the jquery stub did not load.  Can you run it again with this command and post the full debug output, please?

`DEBUG=1 VELOCITY_DEBUG=1 JASMINE_DEBUG=1 mrt`

**Comment by dan335** [comment] 2014-07-12 22:05
[pastebin link of debug output](http://pastebin.com/2p6xqDhB)

Edit: moved log output to pastebin - AVL

**Comment by alanning** [comment] 2014-07-12 22:14
(To prevent this thread from getting so long lets use pastebin or github gists from now on for log output)

It looks like the jquery stub is found and loaded.  Please paste the contents of `tests/a1-package-stubs.js` into a gist so we can check to see if the jQuery stub made it there.

Also to confirm this is the issue, please make a custom stub for jQuery and see if that resolves it.  You can do this by copying [this file](https://raw.githubusercontent.com/alanning/meteor-package-stubber/master/package-stubber/core-stubs/jquery.js) to `tests/jquery-stub.js`

**Comment by dan335** [comment] 2014-07-13 05:04
Here is tests/a1-package-stubs.js https://gist.github.com/dan335/4495eee7f980e102542b

Here is the output after copying that file to tests/jquery-stub.js https://gist.github.com/dan335/29d3e98aa20244d44dfd

**Comment by dan335** [comment] 2014-07-18 02:55
After mrt update I get the jquery error again.

https://gist.github.com/dan335/7a7be440ef0616f8ab3b

**Comment by alanning** [comment] 2014-07-18 03:00
Does that mean you were not getting the error for a while and it recently came back?

**Comment by dan335** [comment] 2014-07-18 03:01
Yep

**Comment by alanning** [comment] 2014-07-18 03:01
So what got it working before?

**Comment by dan335** [comment] 2014-07-18 03:02
No idea.

**Comment by alanning** [comment] 2014-07-18 03:03
Please try adding the package-stubber package to your app directly and then specifying older versions until you find the one that works.  You should be able to specify a version in smart.json, i think.  

`mrt update` may complain so if it does, use `mrt update --force`

**Comment by alanning** [comment] 2014-07-18 03:05
Here's how to specify a version in smart.json:

``` js
"roles": {
  "version": "1.0.1"
}
```

Source: https://github.com/oortcloud/meteorite/#example-smartjson

**Comment by dan335** [comment] 2014-07-18 03:05
By package stubber do you mean this file that you linked above? https://raw.githubusercontent.com/alanning/meteor-package-stubber/master/package-stubber/core-stubs/jquery.js

**Comment by alanning** [comment] 2014-07-18 03:09
There's an actual meteor smart package called "package-stubber" that jasmine-unit uses.  I suspect the issue is somewhere in that package.

It's pulled in automatically by meteorite since jasmine-unit depends on it (you'll see the symbolic link in your `packages` directory).  But if you add it directly to your app's `smart.json` file you can work backwards through the different versions and find the one that works.

The latest version is "0.0.11" which does not seem to work for you.  Repo and history here:
https://github.com/alanning/meteor-package-stubber/blob/master/History.md

**Comment by dan335** [comment] 2014-07-18 03:10
works with jasmine-unit 0.1.23
fails with jasmine-unit 0.1.24

**Comment by dan335** [comment] 2014-07-18 03:12
Also getting this error, but that's another issue. It's new after mrt update.

https://gist.github.com/dan335/2f47ef4c708fa4932fcd

**Comment by alanning** [comment] 2014-07-18 03:12
Interesting.  So that means there's probably a file in your tests directory that has the word "helper" in it which is causing the trouble.  Can you please have a check? 

Edit:  to be clear I mean the word "helper" in the filename. ex.  fooHelper.js

**Comment by dan335** [comment] 2014-07-18 03:15
in the filename?  Nothing with helper in it. Or in the files.

**Comment by alanning** [comment] 2014-07-18 03:21
oh, I forgot that with version 0.1.23 the package-stubber wasn't loaded (its loaded by a "helper").  So that's why  you weren't seeing the error there.

At this point I'm going to need a public repo to continue debugging this issue.  When you have time please publish a repro to github.  It may be as simple as just a hello world meteor app with the same packages loaded as your main app.  That bootstrap-slider one looks like a likely candidate.

**Comment by dan335** [comment] 2014-07-18 03:27
https://github.com/dan335/stuberror

It has both the iron-router error and the jquery error.

**Comment by ghost** [comment] 2014-07-18 09:18
@alanning One issue is that iron-router is stubbed manually. It should not do this because there is a community stub for iron-router.

**Comment by alanning** [comment] 2014-07-18 22:56
Fixed in https://github.com/alanning/meteor-package-stubber/commit/452b7400a768591a3369da08cad7c43c1682f879

Error reproduced in 'stubError' app...

`Error loading app files Cannot read property 'fn' of undefined TypeError: Cannot read property 'fn' of undefined`

... was caused by `bootstrap-slider` hard-coding `window.jQuery`.  In nodejs the global context is actually an object called `global` rather than `window`.  There is a `window` object supplied by node but it is not actually the same as the global context.  

Fix was to attach the jquery stub to not only the global context but also explicitly set `window.jQuery`.

**Closed as completed by alanning** 2014-07-18 22:56 UTC

**Comment by alanning** [comment] 2014-07-18 22:59
Btw, `jasmine-unit` automatically uses the latest version of `package-stubber` so running...

`mrt update` 

...will pull in the latest version (which has this fix).
